server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autoshop
    username: root
    password: 125512
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: xyz.huanxicloud.autoshop.dao.pojo
